### ISSUE TITLE
Packages with package.xml only in 'release' repos don't appear

### ISSUE THREAD

**Issue by rkent** [ros-infrastructure/rosindex#409]
There are a number of packages that have valid repositories, but their packages do not appear. An example of this is rotconv.

rosdistro entry show this:
```yaml
  rot_conv_lib:
    release:
      packages:
      - rot_conv
      tags:
        release: release/rolling/{package}/{version}
      url: https://github.com/ros2-gbp/rot_conv_lib-release.git
      version: 1.1.0-3
    source:
      type: git
      url: https://github.com/AIS-Bonn/rot_conv_lib.git
      version: master
    status: maintained
```
In rosindex, the[ repository appears](https://index.ros.org/r/rot_conv_lib/), but it shows no packages.

What is going on is that this package (and others) do not have a package.xml file in their 'source' repository, but it only appears in the 'release' repository.

One such culprit, [urfdom_headers](https://github.com/ros/urdfdom_headers) has this explanation in their README:
```
Using with ROS

If you choose to check this repository out for use with ROS, be aware that the necessary package.xml
is not included in this repo but instead is added in during the ROS release process. To emulate this, pull
the appropriate file into this repository using the following format. Be sure to replace the ALLCAPS words
with the appropriate terms:

wget https://raw.github.com/ros-gbp/urdfdom_headers-release/debian/ROS_DISTRO/UBUNTU_DISTRO/urdfdom_headers/package.xml

For example:

wget https://raw.github.com/ros-gbp/urdfdom_headers-release/debian/hydro/precise/urdfdom_headers/package.xml

```
I don't really understand how this generated-at-release package.xml works, but rosindex needs to support it.
